# Generated by Django 4.2.3 on 2024-09-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_name_alter_event_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
