# Generated by Django 4.2.3 on 2024-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
