# Generated by Django 5.1.1 on 2024-09-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='register_amount',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
