# Generated by Django 5.1.1 on 2024-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_incharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incharge',
            name='events',
        ),
        migrations.AddField(
            model_name='incharge',
            name='category',
            field=models.ManyToManyField(related_name='eventIncharge', to='events.category'),
        ),
    ]
