# Generated by Django 4.2.3 on 2024-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_participant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
