# Generated by Django 4.2.3 on 2024-09-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_registration_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_proof',
        ),
    ]
