# Generated by Django 5.1.1 on 2024-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day', 'timing']},
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('day1', 'Day 1'), ('day2', 'Day 2'), ('day3', 'Day 3')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='timing',
            field=models.CharField(default='11AM-1PM', max_length=20),
            preserve_default=False,
        ),
    ]
