# Generated by Django 4.2.3 on 2024-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_options_event_day_event_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='total_price',
        ),
        migrations.AddField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
