# Generated by Django 5.1.1 on 2024-10-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_registration_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='college',
            field=models.CharField(default='gceb', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='department',
            field=models.CharField(default='mech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.CharField(default=3, max_length=10, verbose_name=[('1', '1 year'), ('2', '2 year'), ('3', '3 year'), ('4', '4 year')]),
            preserve_default=False,
        ),
    ]
